# Generated by Django 3.2.20 on 2023-09-06 16:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(max_length=255)),
                ('Keywords', models.CharField(max_length=500)),
                ('Note', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
