# Generated by Django 3.2.20 on 2023-09-06 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='Keywords',
            new_name='keywords',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='Note',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='Heading',
            new_name='title',
        ),
    ]
