# Generated by Django 3.2.20 on 2023-09-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20230906_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='text',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
