# Generated by Django 3.2.20 on 2023-09-07 02:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_notes_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
