# Generated by Django 3.2.20 on 2023-09-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_notes_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
