# Generated by Django 3.2.20 on 2023-09-07 06:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_notes_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='Note_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
